"""Turns potrace's ink.svg / bolt.svg into an editable layered SVG and
SwiftUI Shapes normalised to a unit rect. Re-run after editing the masks."""
import re

def parse(path_file):
    svg = open(path_file).read()
    H = float(re.search(r'viewBox="0 0 [\d.]+ ([\d.]+)"', svg).group(1))
    subpaths = []
    for d in re.findall(r'<path d="([^"]+)"', svg, re.S):
        toks = re.findall(r'[MmCcLlZz]|-?\d+\.?\d*', d)
        i, cmd, x, y, sx, sy, cur = 0, None, 0.0, 0.0, 0.0, 0.0, None
        def num():
            nonlocal i
            v = float(toks[i]); i += 1; return v
        while i < len(toks):
            t = toks[i]
            if re.match(r'[A-Za-z]', t):
                cmd = t; i += 1
                if cmd in 'Zz':
                    cur.append(('Z',)); x, y = sx, sy
                    continue
            if cmd in 'Mm':
                dx, dy = num(), num()
                x, y = (x + dx, y + dy) if cmd == 'm' and cur is not None else (dx, dy)
                sx, sy = x, y
                cur = [('M', x, y)]; subpaths.append(cur)
                cmd = 'l' if cmd == 'm' else 'L'
            elif cmd in 'Ll':
                dx, dy = num(), num()
                x, y = (x + dx, y + dy) if cmd == 'l' else (dx, dy)
                cur.append(('L', x, y))
            elif cmd in 'Cc':
                p = [num() for _ in range(6)]
                if cmd == 'c':
                    p = [x + p[0], y + p[1], x + p[2], y + p[3], x + p[4], y + p[5]]
                cur.append(('C', *p)); x, y = p[4], p[5]
    # potrace: translate(0,H) scale(0.1,-0.1)
    def tr(px, py): return px * 0.1, H - py * 0.1
    out = []
    for sp in subpaths:
        seg = []
        for s in sp:
            if s[0] == 'Z': seg.append(s); continue
            pts = [tr(s[k], s[k + 1]) for k in range(1, len(s), 2)]
            seg.append((s[0], *[c for p in pts for c in p]))
        out.append(seg)
    return out

layers = {'ink': parse('ink.svg'), 'bolt': parse('bolt.svg')}
xs = [s[k] for l in layers.values() for sp in l for s in sp if s[0] != 'Z' for k in range(1, len(s), 2)]
ys = [s[k] for l in layers.values() for sp in l for s in sp if s[0] != 'Z' for k in range(2, len(s), 2)]
minx, miny, W, H = min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)
S = max(W, H)

def norm(layer):
    res = []
    for sp in layer:
        seg = []
        for s in sp:
            if s[0] == 'Z': seg.append(s); continue
            vals = list(s[1:])
            for k in range(0, len(vals), 2):
                vals[k] = (vals[k] - minx) / W
                vals[k + 1] = (vals[k + 1] - miny) / H
            seg.append((s[0], *vals))
        res.append(seg)
    return res

def svg_d(layer, scale_x, scale_y):
    parts = []
    for sp in layer:
        for s in sp:
            if s[0] == 'Z': parts.append('Z'); continue
            v = s[1:]
            parts.append(s[0] + ' ' + ' '.join(f'{v[k] * (scale_x if k % 2 == 0 else scale_y):.1f}' for k in range(len(v))))
    return ' '.join(parts)

n = {k: norm(v) for k, v in layers.items()}
VW, VH = 1000, round(1000 * H / W)
open('bingeki-mark.svg', 'w').write(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VW} {VH}">
  <!-- Two layers, edit freely: "ink" (the B frame) and "bolt" (the red strike). -->
  <path id="ink" fill="#111111" fill-rule="evenodd" d="{svg_d(n['ink'], VW, VH)}"/>
  <path id="bolt" fill="#E51E2A" fill-rule="evenodd" d="{svg_d(n['bolt'], VW, VH)}"/>
</svg>
''')

def swift_body(layer):
    lines = []
    for sp in layer:
        for s in sp:
            if s[0] == 'Z': lines.append('        p.closeSubpath()'); continue
            v = [f'{c:.4f}' for c in s[1:]]
            pt = lambda a, b: f'pt({a}, {b})'
            if s[0] == 'M': lines.append(f'        p.move(to: {pt(v[0], v[1])})')
            elif s[0] == 'L': lines.append(f'        p.addLine(to: {pt(v[0], v[1])})')
            else: lines.append(f'        p.addCurve(to: {pt(v[4], v[5])}, control1: {pt(v[0], v[1])}, control2: {pt(v[2], v[3])})')
    return '\n'.join(lines)

def shape(name, doc, layer):
    return f'''/// {doc}
struct {name}: Shape {{
    func path(in rect: CGRect) -> Path {{
        var p = Path()
        func pt(_ x: CGFloat, _ y: CGFloat) -> CGPoint {{
            CGPoint(x: rect.minX + x * rect.width, y: rect.minY + y * rect.height)
        }}
{swift_body(layer)}
        return p
    }}
}}
'''

open('../../Core/Components/BKLogoShapes.swift', 'w').write(f'''import SwiftUI

// Generated by design/logo/svg2swift.py from public/logo.png — do not edit
// by hand; edit design/logo/bingeki-mark.svg's masks and re-run instead.
//
// Both shapes share one unit rect, so stacking them in a ZStack of the same
// frame rebuilds the mark; animate each layer independently (offset, scale,
// `.trim` on a stroke for a draw-on effect). Fill with `eoFill: true`.

enum BKLogo {{
    /// Width / height of the full mark.
    static let aspectRatio: CGFloat = {W / H:.4f}
}}

{shape("BKLogoInk", "The B frame (black, white in dark mode).", n['ink'])}
{shape("BKLogoBolt", "The red lightning strike.", n['bolt'])}''')
print('ink subpaths', len(n['ink']), 'bolt subpaths', len(n['bolt']), 'aspect', round(W / H, 4))
